# Generated by Django 5.1 on 2024-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoraccessmodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
    ]
