# Generated by Django 5.1 on 2024-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0002_visitoraccessmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoraccessmodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
