# Generated by Django 5.1 on 2024-09-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_payments', '0003_remove_condopaymentmodel_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CondoPaymentModel',
        ),
    ]
