# Generated by Django 5.1.3 on 2026-05-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_payments', '0006_rename_desciption_condopaymentmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='condopaymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='condopaymentmodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condopaymentmodel',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condopaymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=50),
        ),
    ]
