# Generated by Django 5.1 on 2024-09-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequestmodel_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequestModel',
        ),
    ]
