# Generated by Django 5.1 on 2024-09-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0003_delete_servicerequestmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('request_description', models.TextField(blank=True, default='', null=True)),
                ('service_type', models.CharField(default='Other', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('request_scheduled_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('responsable_staff', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('scheduled_date', models.DateField()),
                ('more_details', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('requester_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
