# Generated by Django 5.1 on 2024-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0009_alter_servicerequestmodel_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='more_details',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
