# Generated by Django 5.1 on 2024-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0010_alter_servicerequestmodel_more_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
