# Generated by Django 5.1 on 2024-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_reservations', '0004_remove_hallreservationmodel_guess_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallreservationmodel',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
