version: '3.8'

services:
  myapp:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile principal para o app, sem dev deps
    ports:
      - 8000:8000
    volumes:
      - ./myapp:/myapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql_sunnyvale

  psql_sunnyvale:
    container_name: psql_sunnyvale
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  test:
    build:
      context: .
      dockerfile: Dockerfile.test # Dockerfile de teste que inclui dev deps
    command: [ "sh", "-c", "pytest -s && coverage report" ]
    environment:
      - DJANGO_SETTINGS_MODULE=sunnyValeConnect.settings
      - TESTING=1
      - PYTHONPATH=/myapp
    volumes:
      - ./myapp:/myapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql_sunnyvale
    profiles:
      - test
