version: '3.8'  # Se não estiver especificado, é bom adicionar a versão do compose.

services:
  myapp:
    container_name: myapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./myapp:/myapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql_sunnyvale

  psql_sunnyvale:
    container_name: psql_sunnyvale
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  test:
    build:
      context: .
    command: ["sh", "-c", "pytest -s && coverage report"] 
    environment:
      - DJANGO_SETTINGS_MODULE=sunnyValeConnect.settings
      - TESTING=1
    env_file:
      - ./dotenv_files/.env 
    volumes:
      - ./myapp:/myapp
      - ./scripts:/scripts
    depends_on:
      - psql_sunnyvale
    profiles: 
      - test
