# Generated by Django 5.1 on 2024-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_reservations', '0005_alter_hallreservationmodel_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallreservationmodel',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
