# Generated by Django 5.1.3 on 2026-06-02 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_household_from_active_membership(apps, schema_editor):
    """For each pre-existing reservation, look up the user's active
    membership and copy its household. Rows without an active membership
    stay with ``household=NULL`` — the service still handles them."""
    HallReservation = apps.get_model("hall_reservations", "HallReservationModel")
    HouseholdMembership = apps.get_model("households", "HouseholdMembership")
    for r in HallReservation.objects.filter(
        household__isnull=True, reservation_user__isnull=False
    ):
        membership = (
            HouseholdMembership.objects.filter(
                user_id=r.reservation_user_id, status="ACTIVE"
            )
            .order_by("id")
            .first()
        )
        if membership:
            r.household_id = membership.household_id
            r.save(update_fields=["household"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hall_reservations', '0008_alter_hallreservationmodel_reservation_user'),
        ('households', '0002_membershipdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hallreservationmodel',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_reservations', to='households.household'),
        ),
        migrations.AlterField(
            model_name='hallreservationmodel',
            name='reservation_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            backfill_household_from_active_membership, noop
        ),
    ]
