# Generated by Django 5.1.3 on 2026-06-02 18:17

from django.db import migrations, models


def backfill_existing_to_approved(apps, schema_editor):
    """Pre-existing bookings were created before the approval flow,
    so they're treated as already-approved."""
    HallReservationModel = apps.get_model("hall_reservations", "HallReservationModel")
    HallReservationModel.objects.update(status="APPROVED")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hall_reservations', '0010_hallreservationmodel_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallreservationmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(backfill_existing_to_approved, noop),
    ]
