# Generated by Django 5.2.15 on 2026-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('service_type', models.CharField(choices=[('CLEANING', 'Extra cleaning'), ('MAINTENANCE', 'General maintenance'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('SECURITY', 'Security'), ('LANDSCAPING', 'Landscaping'), ('PEST_CONTROL', 'Pest control'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=10)),
                ('request_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
