# Generated by Django 5.1 on 2024-09-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynotificationmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
