# Generated by Django 5.2.15 on 2026-07-06 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NAMED', 'Named'), ('APARTMENT', 'Apartment'), ('APARTMENT_BLOCK', 'Apartment block')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('apartment', models.CharField(blank=True, default='', max_length=10)),
                ('block', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='condominiums.condominium')),
            ],
            options={
                'ordering': ['kind', 'block', 'apartment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('RESIDENT', 'Resident')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_ADMIN', 'Pending admin approval'), ('PENDING_OWNER', 'Pending owner approval'), ('ACTIVE', 'Active'), ('LEFT', 'Left')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='units.unit')),
            ],
            options={
                'ordering': ['unit_id', 'id'],
            },
        ),
    ]
