# Generated by Django 5.2.15 on 2026-07-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'NAMED')), fields=('condominium', 'name'), name='uniq_unit_condominium_name_named'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'APARTMENT')), fields=('condominium', 'apartment'), name='uniq_unit_condominium_apartment'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'APARTMENT_BLOCK')), fields=('condominium', 'apartment', 'block'), name='uniq_unit_condominium_apartment_block'),
        ),
        migrations.AddConstraint(
            model_name='unitmembership',
            constraint=models.UniqueConstraint(fields=('unit', 'user'), name='uniq_unit_membership_unit_user'),
        ),
    ]
