# Generated by Django 5.1.3 on 2026-07-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='block',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
