# Generated by Django 5.2.16 on 2026-07-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unit_block_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMembershipDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_kind', models.CharField(max_length=20)),
                ('unit_name', models.CharField(blank=True, default='', max_length=100)),
                ('unit_apartment', models.CharField(blank=True, default='', max_length=10)),
                ('unit_block', models.CharField(blank=True, default='', max_length=50)),
                ('unit_display_name', models.CharField(max_length=160)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_username', models.CharField(blank=True, default='', max_length=150)),
                ('target_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_decisions', to='units.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['unit', '-created_at'], name='units_unitm_unit_id_fdf61f_idx')],
            },
        ),
    ]
