# Generated by Django 5.1.3 on 2026-07-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unitmembershipdecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmembership',
            name='status',
            field=models.CharField(choices=[('PENDING_EMAIL', 'Pending email verification'), ('PENDING_ADMIN', 'Pending admin approval'), ('PENDING_OWNER', 'Pending owner approval'), ('ACTIVE', 'Active'), ('LEFT', 'Left')], max_length=20),
        ),
    ]
