# Generated by Django 5.1.3 on 2026-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_pending_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmembershipdecision',
            name='actor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='unitmembershipdecision',
            name='actor_role',
            field=models.CharField(blank=True, default='', help_text='Capacity used for the decision: ADMIN or OWNER.', max_length=20),
        ),
    ]
