# Generated by Django 5.2.15 on 2026-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#d97706', max_length=7)),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7)),
                ('accent_color', models.CharField(default='#111827', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='condominiums/logos/')),
                ('welcome_message', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
