# Generated by Django 5.1.3 on 2026-07-21 21:16

import condominiums.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominium',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=condominiums.modules.default_enabled_modules, help_text='Optional product modules available to this condominium. Frontend only — does not gate backend APIs.'),
        ),
    ]
