# Generated by Django 5.2.15 on 2026-07-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('host_user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VisitorGroupMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='visitor_access.visitorgroupmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VisitorAccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('checkin_date_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_date_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_code', models.CharField(max_length=10)),
                ('checkout_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('CHECKED_IN', 'Check-in feito'), ('CHECKED_OUT', 'Concluído'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'Não compareceu'), ('EXPIRED', 'Expirado sem checkout')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='', max_length=150, null=True)),
                ('qr_access_enabled', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('access_code', models.CharField(blank=True, default=None, max_length=10, null=True, unique=True)),
                ('host_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitor_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='visitor_access.visitorgroupmodel')),
            ],
        ),
    ]
