# Generated by Django 5.1 on 2024-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0003_visitoraccessmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoraccessmodel',
            name='link_checkin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccessmodel',
            name='link_checkout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
