# Generated by Django 5.1 on 2024-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0004_visitoraccessmodel_link_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoraccessmodel',
            name='checkin_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
