# Generated by Django 5.2.14 on 2026-05-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_access', '0007_alter_visitoraccessmodel_checkout_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoraccessmodel',
            name='link_checkin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitoraccessmodel',
            name='link_checkout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
