# Generated by Django 5.1.3 on 2026-07-18 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESERVATION_APPROVED', 'Reservation approved'), ('RESERVATION_REJECTED', 'Reservation rejected'), ('VISITOR_CHECKIN', 'Visitor check-in'), ('VISITOR_ARRIVAL', 'Visitor arrival'), ('DELIVERY', 'Delivery'), ('UNIT_JOIN_REQUEST', 'Unit join request'), ('UNIT_REQUEST_APPROVED', 'Unit request approved'), ('UNIT_REQUEST_REJECTED', 'Unit request rejected'), ('SERVICE_REQUEST_RESPONDED', 'Service request responded'), ('GENERIC', 'Generic')], default='GENERIC', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='condominiums.condominium')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_7c909b_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_80be74_idx')],
            },
        ),
    ]
