# Generated by Django 5.1.3 on 2026-06-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_household_from_active_membership(apps, schema_editor):
    """Existing reservations only knew their ``reservation_user``. For
    each, look up the user's currently active membership and copy its
    household onto the reservation row. Rows whose user has no active
    membership (or whose user was already nulled out by SET_NULL) stay
    with ``household=NULL`` and the service can still handle them.
    """
    BBQReservation = apps.get_model("bbq_reservations", "BBQReservationModel")
    HouseholdMembership = apps.get_model("households", "HouseholdMembership")
    for r in BBQReservation.objects.filter(
        household__isnull=True, reservation_user__isnull=False
    ):
        membership = (
            HouseholdMembership.objects.filter(
                user_id=r.reservation_user_id, status="ACTIVE"
            )
            .order_by("id")
            .first()
        )
        if membership:
            r.household_id = membership.household_id
            r.save(update_fields=["household"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_reservations', '0003_alter_bbqreservationmodel_reservation_user'),
        ('households', '0002_membershipdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bbqreservationmodel',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbq_reservations', to='households.household'),
        ),
        migrations.AlterField(
            model_name='bbqreservationmodel',
            name='reservation_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            backfill_household_from_active_membership, noop
        ),
    ]
