# Generated by Django 5.1.3 on 2026-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_reservations', '0004_bbqreservationmodel_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbqreservationmodel',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbqreservationmodel',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
