# Generated by Django 5.1.3 on 2026-06-02 18:17

from django.db import migrations, models


def backfill_existing_to_approved(apps, schema_editor):
    """Pre-existing bookings were created before the approval flow,
    so they're treated as already-approved."""
    BBQReservationModel = apps.get_model("bbq_reservations", "BBQReservationModel")
    BBQReservationModel.objects.update(status="APPROVED")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_reservations', '0005_bbqreservationmodel_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbqreservationmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(backfill_existing_to_approved, noop),
    ]
