# Generated by Django 5.1 on 2024-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condopaymentmodel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
