# Generated by Django 5.1 on 2024-09-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_payments', '0002_alter_condopaymentmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='payer_user',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='condopaymentmodel',
            name='updated_at',
        ),
    ]
