# Generated by Django 5.2.15 on 2026-06-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_apartment', models.CharField(max_length=10)),
                ('household_block', models.CharField(blank=True, default='', max_length=10)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_username', models.CharField(blank=True, default='', max_length=150)),
                ('target_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(max_length=10)),
                ('block', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_ADMIN', 'Pending admin approval'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='PENDING_ADMIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='condominiums.condominium')),
            ],
            options={
                'ordering': ['block', 'apartment'],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(blank=True, default='', max_length=11)),
                ('relationship', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='households.household')),
            ],
            options={
                'ordering': ['household_id', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HOLDER', 'Holder'), ('RESIDENT', 'Resident')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_HOLDER', 'Pending holder approval'), ('PENDING_ADMIN', 'Pending admin approval'), ('ACTIVE', 'Active'), ('LEFT', 'Left')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='households.household')),
            ],
            options={
                'ordering': ['household_id', 'id'],
            },
        ),
    ]
