# Generated by Django 5.1.3 on 2026-06-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_apartment', models.CharField(max_length=10)),
                ('household_block', models.CharField(blank=True, default='', max_length=10)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_username', models.CharField(blank=True, default='', max_length=150)),
                ('target_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='households.household')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['household', '-created_at'], name='households__househo_08070b_idx')],
            },
        ),
    ]
