# Generated by Django 5.2.15 on 2026-06-28 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='households.household'),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(fields=('condominium', 'apartment', 'block'), name='uniq_household_condominium_apartment_block'),
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(fields=('household', 'user'), name='uniq_membership_household_user'),
        ),
        migrations.AddIndex(
            model_name='membershipdecision',
            index=models.Index(fields=['household', '-created_at'], name='households__househo_08070b_idx'),
        ),
    ]
