# Generated by Django 5.2.4 on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("condominiums", "0001_initial"),
        ("units", "0004_unitmembershipdecision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservableLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condominium", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservable_locations", to="condominiums.condominium")),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reservation_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("guest_count", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condominium", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="condominiums.condominium")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="reservations.reservablelocation")),
                ("reservation_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reservations", to=settings.AUTH_USER_MODEL)),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reservations", to="units.unit")),
            ],
            options={
                "ordering": ["-reservation_date", "start_time", "id"],
                "indexes": [
                    models.Index(fields=["condominium", "reservation_date"], name="reservation_condomi_821bf4_idx"),
                    models.Index(fields=["location", "reservation_date"], name="reservation_locatio_71619c_idx"),
                    models.Index(fields=["condominium", "status"], name="reservation_condomi_93e1dd_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("guest_count__isnull", True), ("guest_count__gte", 0), _connector="OR"), name="reservation_guest_count_positive")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reservablelocation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("condominium"),
                name="uniq_reservable_location_condo_name_ci",
            ),
        ),
    ]
