# Generated by Django 5.1.3 on 2026-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservablelocation',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
