# Generated by Django 5.1.3 on 2026-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservablelocation_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservablelocation',
            name='icon',
            field=models.CharField(blank=True, choices=[('outdoor_grill', 'Barbecue'), ('celebration', 'Party'), ('sports_court', 'Sports court'), ('sports_field', 'Sports field'), ('meeting_room', 'Meeting room'), ('fitness_center', 'Fitness center')], default='', max_length=100),
        ),
    ]
