# Generated by Django 5.1.3 on 2026-07-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0001_initial'),
        ('reservations', '0003_alter_reservablelocation_icon'),
        ('units', '0006_decision_actor_role_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, default='', max_length=150)),
                ('location_icon', models.CharField(blank=True, default='', max_length=100)),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('unit_display_name', models.CharField(blank=True, default='', max_length=160)),
                ('target_username', models.CharField(blank=True, default='', max_length=150)),
                ('target_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_email', models.EmailField(blank=True, default='', max_length=254)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_full_name', models.CharField(blank=True, default='', max_length=150)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('actor_role', models.CharField(blank=True, default='', help_text='Capacity used for the decision: ADMIN.', max_length=20)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_decisions', to='condominiums.condominium')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reservations.reservablelocation')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='reservations.reservation')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='units.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['condominium', '-created_at'], name='reservation_condomi_023d8d_idx'), models.Index(fields=['location', '-created_at'], name='reservation_locatio_05d029_idx')],
            },
        ),
    ]
