# Generated by Django 5.2.15 on 2026-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_holder_name', models.CharField(blank=True, default='', max_length=150)),
                ('notified_holder_email', models.EmailField(blank=True, default='', max_length=254)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('delivery_platform', models.CharField(choices=[('ifood', 'iFood'), ('rappi', 'Rappi'), ('amazon', 'Amazon'), ('mercado_livre', 'Mercado Livre'), ('magalu', 'Magalu'), ('shopee', 'Shopee'), ('correios', 'Correios'), ('other', 'Outro')], default='other', max_length=20)),
                ('delivery_from', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('delivery_to', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='Low', max_length=50)),
            ],
        ),
    ]
