# Generated by Django 5.1 on 2024-09-10 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('delivery_platform', models.CharField(choices=[('ifood', 'Ifood'), ('rappi', 'Rappi'), ('uber eats', 'Uber Eats'), ('doordash', 'DoorDash'), ('just eat', 'Just Eat'), ('other', 'Other')], default='Other', max_length=20)),
                ('delivery_from', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('delivery_to', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='Low', max_length=50)),
                ('user_to_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
