# Generated by Django 5.2.15 on 2026-07-06 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunnyValeNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('NOTICE', 'Aviso'), ('MAINTENANCE', 'Manutenção'), ('EVENT', 'Evento')], default='NOTICE', max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('author_role', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='condominiums.condominium')),
            ],
        ),
    ]
