# Generated by Django 5.1.3 on 2026-05-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunny_vale_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunnyvalenewsmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
